version: "3.9"

services:
  web:
    build: ./bot
    container_name: web_bot
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bot/:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG='True'
    env_file:
      - ./.env.dev
  bot:
    build: ./bot
    container_name: tg_mr_bot
    command: python run_pooling.py
    volumes:
      - ./bot/:/code
    env_file:
      - ./.env.dev
    depends_on:
      - web