version: "3.9"

services:
  web:
    build: .
    container_name: web_bot
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG='True'
    env_file:
      - ./.env.dev
    entrypoint: /entrypoint.sh